import React, { useState } from "react";
import Head from "next/head";

export default function Home() {
	const [username, setUsername] = useState("");
	const [password, setPassword] = useState("");
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<form
					action=""
					onSubmit={(e) => handleSubmit(e)}
					className="flex flex-row h-10"
				>
					<label htmlFor="username">Username</label>
					<input
						type="text"
						name="username"
						className="m-1 p-2 bg-white rounded-xl shadow-lg flex items-center space-x-4"
						onChange={(e) => setUsername(e.target.value)}
					/>
					<label htmlFor="password">Password</label>
					<input
						type="password"
						name="password"
						className="m-1 p-2 bg-white rounded-xl shadow-lg flex items-center space-x-4"
						onChange={(e) => setPassword(e.target.value)}
					/>

					<button
						type="submit"
						className="hover:rounded bg-blue-900 text-white w-40"
					>
						Log in
					</button>
				</form>
			</main>
		</>
	);
}
